### ISSUE TITLE
java.lang.RuntimeException: Unknown animator name: translate

### ISSUE THREAD

**Issue by veiz** [vignesh-iopex/confirmdialog#4]
SDK 22.
```
    java.lang.RuntimeException: Unknown animator name: translate
            at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:592)
            at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:551)
            at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:122)
            at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:102)
            at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:87)
            at android.app.FragmentManagerImpl.loadAnimator(FragmentManager.java:747)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:962)
            at android.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1172)
            at android.app.BackStackRecord.run(BackStackRecord.java:785)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
            at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by vignesh-iopex** [comment]
Had to use object animator for non v4 `FragmentManager` transaction, I have pushed a release 1.0.3 will be available in 30 minutes from maven central.
